export interface ClientProject {
  id: string;
  title: string;
  clientName: string;
  category: 'web-development' | 'wordpress' | 'web-app' | 'ecommerce';
  categoryLabel: string;
  liveUrl: string;
  image: string;
  description: string;
  tags: string[];
  metrics?: string;
  featured?: boolean;
}

export const portfolioCategories = [
  { key: 'all', label: 'All Projects' },
  { key: 'web-development', label: 'Web Development' },
  { key: 'web-app', label: 'Software & Web Apps' },
  { key: 'ecommerce', label: 'E-Commerce' },
  { key: 'wordpress', label: 'WordPress / CMS' },
] as const;

export const clientProjects: ClientProject[] = [
  {
    id: 'etenderbd',
    title: 'eTenderBD — Government Tenders & e-Procurement Portal',
    clientName: 'eTenderBD',
    category: 'web-app',
    categoryLabel: 'Software & Web Apps',
    liveUrl: 'https://etenderbd.com/',
    image: '/assets/images/portfolio/etenderbd.jpeg',
    description: 'A national tender aggregation and eGP intelligence platform providing real-time tender tracking, daily procurement notices, and automated bidding alerts for contractors across Bangladesh.',
    tags: ['React', 'Next.js', 'e-Procurement', 'Real-Time Alerts', 'Tailwind CSS'],
    metrics: 'Daily Tender Aggregation',
    featured: true,
  },
  {
    id: 'bcns',
    title: 'Bangladesh Child Neurology Society (BCNS)',
    clientName: 'BCNS',
    category: 'wordpress',
    categoryLabel: 'WordPress / CMS',
    liveUrl: 'https://www.bcns.org.bd/',
    image: '/assets/images/portfolio/bcns.jpeg',
    description: 'The official digital portal for Bangladesh Child Neurology Society dedicated to pediatric neurology clinical research, healthcare provider networking, and medical resources.',
    tags: ['Medical Society', 'Next.js', 'Research Library', 'Member Directory'],
    metrics: 'National Medical Network',
    featured: true,
  },
  {
    id: 'excelinsider',
    title: 'Excel Insider — Pro Tutorials, Tools & Templates',
    clientName: 'Excel Insider',
    category: 'wordpress',
    categoryLabel: 'WordPress / CMS',
    liveUrl: 'https://excelinsider.com/',
    image: '/assets/images/portfolio/excelinsider.jpeg',
    description: 'An authoritative spreadsheet media platform offering professional Excel and Google Sheets tutorials, automated business templates, and productivity tools.',
    tags: ['WordPress / CMS', 'SEO Optimization', 'Custom Templates', 'Media Platform'],
    metrics: 'High Organic Reach',
    featured: true,
  },
  {
    id: 'webblyhosting',
    title: 'WebblyHosting — Cloud & Domain Infrastructure',
    clientName: 'WebblyHosting',
    category: 'web-development',
    categoryLabel: 'Web Development',
    liveUrl: 'https://webblyhosting.com/en',
    image: '/assets/images/portfolio/webblyhosting.png',
    description: 'High-performance cloud hosting and domain registration platform built with blazing-fast SSD storage, automated SSL provisioning, cPanel integration, and 99.9% uptime reliability.',
    tags: ['Cloud Hosting', 'Next.js', 'Infrastructure', 'Billing Automation'],
    metrics: '99.9% Uptime Guarantee',
    featured: true,
  },
  {
    id: 'omnistreams',
    title: 'OmniStreams — OTT Video Streaming & Media Platform',
    clientName: 'OmniStreams',
    category: 'web-app',
    categoryLabel: 'Software & Web Apps',
    liveUrl: 'https://omnistreams.co/en',
    image: '/assets/images/portfolio/omnistreams.jpg',
    description: 'A high-throughput digital video on-demand and OTT streaming platform engineered with Next.js, cloud media infrastructure, multi-device playback, and custom content delivery.',
    tags: ['Next.js', 'OTT Streaming', 'Cloud Architecture', 'Video on Demand', 'Tailwind CSS'],
    metrics: 'High-Concurrency Streaming',
    featured: true,
  },
  {
    id: 'approvalstore',
    title: 'Approval Store — Auto Financing Platform Canada',
    clientName: 'Approval Store',
    category: 'web-app',
    categoryLabel: 'Software & Web Apps',
    liveUrl: 'https://approvalstore.ca/',
    image: '/assets/images/portfolio/approvalstore.png',
    description: 'All-inclusive Canadian automotive financing pre-approval platform engineered for fast loan applications, flexible credit underwriting, and streamlined dealer lead processing.',
    tags: ['React', 'Vite', 'FinTech Pre-Approval', 'Tailwind CSS', 'Lead Automation'],
    metrics: 'Fast Canadian Pre-Approval',
    featured: true,
  },
  {
    id: 'shailoom',
    title: 'Shailoom — Modern Fashion & Lifestyle E-Commerce',
    clientName: 'Shailoom',
    category: 'ecommerce',
    categoryLabel: 'E-Commerce',
    liveUrl: 'https://www.shailoom.com/',
    image: '/assets/images/portfolio/shailoom.png',
    description: 'A sleek, modern lifestyle and fashion e-commerce storefront engineered with Next.js for lightning-fast catalog navigation, dynamic cart management, and seamless mobile checkout.',
    tags: ['Next.js', 'E-Commerce Storefront', 'Tailwind CSS', 'Mobile First CRO'],
    metrics: 'Sub-Second Page Loads',
    featured: true,
  },
  {
    id: 'playgroundfitnex',
    title: 'PGX — Lifestyle, Fitness & Performance Gear',
    clientName: 'Playground Fitnex',
    category: 'ecommerce',
    categoryLabel: 'E-Commerce',
    liveUrl: 'https://playgroundfitnex.com/',
    image: '/assets/images/portfolio/playgroundfitnex.png',
    description: 'High-performance athletic lifestyle shop showcasing premium fitness gear, training apparel, and everyday workout essentials with a bold visual brand experience.',
    tags: ['Next.js', 'Fitness E-Commerce', 'Performance UI', 'Tailwind CSS'],
    metrics: 'High-Converting Storefront',
    featured: true,
  },
  {
    id: 'playgroundx',
    title: 'PlayGroundX — Creator & Fan Engagement Platform',
    clientName: 'Playgroundx',
    category: 'web-app',
    categoryLabel: 'Software & Web Apps',
    liveUrl: 'https://playgroundx.vip/',
    image: '/assets/images/portfolio/playgroundx.png',
    description: 'An interactive creator community and monetization platform enabling digital creators to host exclusive VIP content, connect directly with fans, and build recurring revenue streams.',
    tags: ['Creator Economy', 'Next.js', 'VIP Subscriptions', 'Interactive Community'],
    metrics: 'High-Engagement Fan Hub',
    featured: true,
  },
  {
    id: 'leersports',
    title: 'LEER Sports — Elite Fitness Training & Creator Platform',
    clientName: 'LEER Sports',
    category: 'web-development',
    categoryLabel: 'Web Development',
    liveUrl: 'https://leersports.cliplyx.com/',
    image: '/assets/images/portfolio/leersports.png',
    description: 'Elite athletic coaching and creator portal built with structured workout programs across martial arts, strength conditioning, endurance training, and sport-specific performance.',
    tags: ['Next.js', 'Supabase', 'Coaching Platform', 'Video Drills', 'Tailwind CSS'],
    metrics: 'Elite Coach Network',
    featured: true,
  },
  {
    id: 'huipper',
    title: 'Huipper — Enterprise Software Solutions & SaaS',
    clientName: 'Huipper',
    category: 'web-development',
    categoryLabel: 'Web Development',
    liveUrl: 'https://huipper.com/',
    image: '/assets/images/portfolio/huipper.png',
    description: 'A global digital engineering platform specializing in ready-made software solutions, custom SaaS platforms, AI-powered products, and enterprise cloud applications.',
    tags: ['Custom SaaS', 'Next.js', 'AI Products', 'Enterprise Architecture'],
    metrics: 'Global Tech Delivery',
    featured: true,
  },
];
