export const privacyPolicyContent = {
    header: {
        title: 'Privacy Policy',
        lastUpdated: 'Last updated: 10 January 2026',
        welcome: {
            title: 'Welcome to Webbly Media',
            text: 'At Webbly Media, your privacy is important to us. This Privacy Policy explains how we collect, use, protect, and share your information when you visit our website or use our services. By using our website, you agree to the practices described in this policy.',
        },
    },
    toc: [
        { id: 'information-collection', label: '1. Information We Collect' },
        { id: 'use-of-information', label: '2. How We Use Your Information' },
        { id: 'cookies', label: '3. Cookies and Tracking Technologies' },
        { id: 'data-protection', label: '4. How We Protect Your Information' },
        { id: 'sharing-information', label: '5. Sharing of Information' },
        { id: 'third-party', label: '6. Third-Party Services and Links' },
        { id: 'data-retention', label: '7. Data Retention' },
        { id: 'privacy-rights', label: '8. Your Privacy Rights' },
        { id: 'children-privacy', label: '9. Children’s Privacy' },
        { id: 'changes', label: '10. Changes to This Privacy Policy' },
        { id: 'contact', label: '11. Contact Us' },
    ],
    sections: [
        {
            id: 'information-collection',
            title: '1. Information We Collect',
            content: [
                'We collect different types of information to provide and improve our services.',
                '1.1 Personal Information',
                'We may collect personal details when you:',
                '- Fill out a contact form',
                '- Request a consultation or quote',
                '- Subscribe to our emails',
                '- Communicate with us directly',
                'This information may include:',
                '- Name',
                '- Email address',
                '- Phone number',
                '- Company name',
                '- Project details or messages',
                '1.2 Non-Personal Information',
                'We automatically collect limited non-personal data, such as:',
                '- IP address',
                '- Browser type',
                '- Device information',
                '- Pages visited',
                '- Time spent on our website',
                'This data helps us understand user behavior and improve website performance.',
            ],
        },
        {
            id: 'use-of-information',
            title: '2. How We Use Your Information',
            content: [
                'We use the collected information to:',
                '- Respond to inquiries and provide services',
                '- Improve our website and user experience',
                '- Communicate project updates and service information',
                '- Send relevant marketing or informational content (only if you opt in)',
                '- Ensure website security and prevent misuse',
                'We never use your information for purposes beyond what is stated here.',
            ],
        },
        {
            id: 'cookies',
            title: '3. Cookies and Tracking Technologies',
            content: [
                'Webbly Media uses cookies and similar technologies to enhance your browsing experience.',
                'Cookies help us:',
                '- Understand how users interact with our website',
                '- Analyze traffic and performance',
                '- Improve functionality and content relevance',
                'You can disable cookies through your browser settings. However, some features of the website may not work properly.',
            ],
        },
        {
            id: 'data-protection',
            title: '4. How We Protect Your Information',
            content: [
                'We take data protection seriously. Our security measures include:',
                '- Secure servers and encrypted connections',
                '- Limited access to personal information',
                '- Regular monitoring for security risks',
                'While no online system is 100% secure, we follow industry-standard practices to protect your data.',
            ],
        },
        {
            id: 'sharing-information',
            title: '5. Sharing of Information',
            content: [
                'We do not sell, rent, or trade your personal information. We may share limited information only when:',
                '- Required by law or legal process',
                '- Working with trusted partners who help us operate our services (under strict confidentiality agreements)',
                'Your data is shared only when necessary and responsibly.',
            ],
        },
        {
            id: 'third-party',
            title: '6. Third-Party Services and Links',
            content: [
                'Our website may include links to third-party tools, platforms, or websites. We are not responsible for the privacy practices or content of those external sites.',
                'We encourage you to review their privacy policies before sharing any personal information.',
            ],
        },
        {
            id: 'data-retention',
            title: '7. Data Retention',
            content: [
                'We retain personal information only as long as necessary to:',
                '- Fulfill service purposes',
                '- Meet legal or business requirements',
                '- Resolve disputes or enforce agreements',
                'Once no longer needed, data is securely deleted.',
            ],
        },
        {
            id: 'privacy-rights',
            title: '8. Your Privacy Rights',
            content: [
                'You have the right to:',
                '- Request access to your personal data',
                '- Ask for corrections or updates',
                '- Request the deletion of your information',
                '- Opt out of marketing communications',
                'To exercise these rights, contact us using the details below.',
            ],
        },
        {
            id: 'children-privacy',
            title: '9. Children’s Privacy',
            content: [
                'Webbly Media does not knowingly collect personal information from children under the age of 13. If you believe a child has shared data with us, please contact us, and we will remove it promptly.',
            ],
        },
        {
            id: 'changes',
            title: '10. Changes to This Privacy Policy',
            content: [
                'We may update this Privacy Policy from time to time to reflect changes in laws, technologies, or our services. Any updates will be posted on this page with an updated date. We encourage you to review this policy periodically.',
            ],
        },
        {
            id: 'contact',
            title: '11. Contact Us',
            content: [
                'If you have any questions or concerns about this Privacy Policy or how we handle your data, please contact us:',
                'Webbly Media',
                'Email: info@webblymedia.com',
                'Website: https://www.webblymedia.com',
                'By using our website, you acknowledge that you have read and understood this Privacy Policy.',
            ],
        },
    ],
};
